### PR TITLE
Add optional explanation field to detections

### PR DESCRIPTION
**Pull request by ryanplasma**
The current behavior of contentctl copies the detection description to both the description and explanation fields in the analytic story page.

This PR adds the option to have an `explanation` field in the detection yml file if one wants to have different content in that area, otherwise it will defer to the content in the `description` field.

This could be expanded on and included in the required fields in the future, but this felt like a good first step.

Image below illustrates the different sections I'm talking about.

image

### CODE REVIEW

**Comment by pyth0n1c** [comment]
Hi @ryanplasma !
Thanks for the contribution and sorry for the delay!  
I am having a chat with the team tomorrow to take a look and we will provide an update 👍

**Comment by ryanplasma** [comment]
No worries! I know yall have a lot going on over there - just wanted to make sure I wasn't missing part of any process.

**Comment by pyth0n1c** [comment]
Hi @ryanplasma !
I noticed a small bug in the PR where the newlines in the explanation field are not properly escaped:
https://github.com/splunk/contentctl/pull/233/files#diff-b3a323469b8602fb9740eaf0a0c78b5adde9de4cceb873ac24be3db133f3327eR10
This ONLY applies to escapeNewlines() function to the description field (I have confirmed this experimentally).
I am closing this PR, but have recreated it with the changes here:
https://github.com/splunk/contentctl/pull/296
And expect to merge it shortly 😄 

Thank you for the PR!

**Comment by pyth0n1c** [comment]
Merged: https://github.com/splunk/contentctl/pull/296

**Comment by ryanplasma** [comment]
> Hi @ryanplasma ! I noticed a small bug in the PR where the newlines in the explanation field are not properly escaped: https://github.com/splunk/contentctl/pull/233/files#diff-b3a323469b8602fb9740eaf0a0c78b5adde9de4cceb873ac24be3db133f3327eR10 This ONLY applies to escapeNewlines() function to the description field (I have confirmed this experimentally). I am closing this PR, but have recreated it with the changes here: #296 And expect to merge it shortly 😄
> 
> Thank you for the PR!

Awesome - thank you!

**Pull request closed without merging**
